os: windows
language: shell
dotnet: 8.0
services:
  - docker

before_install:
  - powershell -Command "choco install dotnet-sdk --version=8.0.100 -y --no-progress"
  - powershell -Command "dotnet --version"
  - powershell -Command "dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org"


before_script:
  - powershell -Command "dotnet restore"

script:
  - powershell -Command "dotnet build --configuration Debug"
  - powershell -Command "dotnet test HelloWorld.Tests/HelloWorld.Tests.csproj --nologo --results-directory:test_coverage --collect:'Code Coverage' --verbosity normal"
