os: windows
language: shell
dotnet: 8.0
services:
  - docker

before_install:
  - powershell -Command "choco install dotnet-sdk --version=8.0.100 -y --no-progress"
  - powershell -Command "Invoke-WebRequest -Uri https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-8.0.0-windows-hosting-bundle-installer -OutFile aspnetcore-runtime-installer.exe"
  - powershell -Command "Start-Process -FilePath .\aspnetcore-runtime-installer.exe -ArgumentList '/quiet', '/norestart' -Wait"

  - powershell -Command "Remove-Item .\$output"

before_script:
  - powershell -Command "dotnet restore"

script:
  - powershell -Command "dotnet build --configuration Debug"
  - powershell -Command "dotnet test HelloWorld.Tests/HelloWorld.Tests.csproj --nologo --results-directory:test_coverage --collect:'Code Coverage' --verbosity normal"
